{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jaudiostream",
    "module": "jaudiostream",
    "version": "1.87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ollie.utils",
          "module": "utils",
          "version": {
            "requires": "1.74"
          }
        }
      ],
      "files": [
        {
          "name": "jaudiostream-1.87.jar",
          "url": "jaudiostream-1.87.jar",
          "size": 42011,
          "sha512": "a94f4795480b90212aa08a06483fc733138771cb90dddac9d9eeddb7ecad89814bedba5679801fef3c7a3da11012b022e4c6f27debfb5711eebc6b277c979bb5",
          "sha256": "73f27053e207a138a0f657899948dce7a534a604c0c6dd55c951afda92fe227a",
          "sha1": "1a25c3fc1fb002cfcf8a8e709f7f6c2c2e5936d4",
          "md5": "22b83585a9e6924b47b33670e60900c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ollie.utils",
          "module": "utils",
          "version": {
            "requires": "1.74"
          }
        }
      ],
      "files": [
        {
          "name": "jaudiostream-1.87.jar",
          "url": "jaudiostream-1.87.jar",
          "size": 42011,
          "sha512": "a94f4795480b90212aa08a06483fc733138771cb90dddac9d9eeddb7ecad89814bedba5679801fef3c7a3da11012b022e4c6f27debfb5711eebc6b277c979bb5",
          "sha256": "73f27053e207a138a0f657899948dce7a534a604c0c6dd55c951afda92fe227a",
          "sha1": "1a25c3fc1fb002cfcf8a8e709f7f6c2c2e5936d4",
          "md5": "22b83585a9e6924b47b33670e60900c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jaudiostream-1.87-sources.jar",
          "url": "jaudiostream-1.87-sources.jar",
          "size": 21210,
          "sha512": "60a75f7bdef0553a4b29c18a396bd2472822fadc02e62d3eb15c814bc53a080d2dbcb1c5ac7e82a42287892abb51901c8c8ef1595112593833af3e40e37541ea",
          "sha256": "396fff3daa0870a183484aba2d591eecb58886f5bad045f5e12f93d74b89c008",
          "sha1": "061cfdf77ef55dc2c7c67d1fd5b2792e1d41d791",
          "md5": "505d4f05355a5ca00baff2f8c919f16b"
        }
      ]
    }
  ]
}
